version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "email-events:1:3"

  consumer:
    environment:
     SPRING_KAFKA_CONSUMER_SERVER: kafka:9092
    container_name: consumer
    depends_on:
      - kafka
    build:
      ../consumer
    ports:
      - 8089:8089

  producer:
    environment:
      SPRING_KAFKA_PRODUCER_SERVER: kafka:9092
    container_name: producer
    depends_on:
      - kafka
    build:
      ../producer
    ports:
      - 8090:8090