server:
  port: 8089
spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: "consumer"
      topic: "email-events"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
